import os
import uuid
import re
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# Create static directory if it doesn't exist
static_dir = os.path.join(os.path.dirname(__file__), "static")
os.makedirs(static_dir, exist_ok=True)

class ClassGenPDF(FPDF):
    def __init__(self, subtitle: str = ""):
        super().__init__()
        self._subtitle = _sanitize_for_latin1(subtitle) if subtitle else ""

    def header(self):
        self.set_font("helvetica", "B", 15)
        self.cell(0, 10, "ClassGen Lesson Plan", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        if self._subtitle:
            self.set_font("helvetica", "I", 10)
            self.cell(0, 6, self._subtitle, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.set_font("helvetica", size=8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 6, f"Generated {datetime.now().strftime('%d %b %Y')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.set_text_color(0, 0, 0)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Generated by ClassGen AI - Page {self.page_no()}", align="C")

def _sanitize_for_latin1(text: str) -> str:
    """Sanitize text for FPDF latin-1 encoded core fonts."""
    replacements = {
        '\u2014': '-',     # em dash
        '\u2013': '-',     # en dash
        '\u2018': "'",     # left single quote
        '\u2019': "'",     # right single quote
        '\u201c': '"',     # left double quote
        '\u201d': '"',     # right double quote
        '\u2022': '-',     # bullet
        '\u2026': '...',   # ellipsis
        '\u00b0': ' deg',  # degree sign
        '\u00d7': 'x',     # multiplication sign
        '\u00f7': '/',     # division sign
        '\u2192': '->',    # right arrow
        '\u2190': '<-',    # left arrow
        '\u2194': '<->',   # left-right arrow
        '\u20a6': 'NGN',   # naira sign
        '\u2032': "'",     # prime
        '\u2033': '"',     # double prime
        '\u2248': '~=',    # approximately equal
        '\u2260': '!=',    # not equal
        '\u2264': '<=',    # less than or equal
        '\u2265': '>=',    # greater than or equal
        '\u221a': 'sqrt',  # square root
        '\u03c0': 'pi',    # pi
        '\u2103': ' deg C', # degree Celsius
        # Subscript digits (common in chemical formulas)
        '\u2080': '0', '\u2081': '1', '\u2082': '2', '\u2083': '3', '\u2084': '4',
        '\u2085': '5', '\u2086': '6', '\u2087': '7', '\u2088': '8', '\u2089': '9',
        # Superscript digits
        '\u2070': '0', '\u00b9': '1', '\u00b2': '2', '\u00b3': '3', '\u2074': '4',
        '\u2075': '5', '\u2076': '6', '\u2077': '7', '\u2078': '8', '\u2079': '9',
        # Subscript +/-
        '\u208a': '+', '\u208b': '-',
    }
    for search, replace in replacements.items():
        text = text.replace(search, replace)
    # Strip any remaining non-latin-1 characters
    return text.encode('latin-1', 'ignore').decode('latin-1')


def _safe_line(line: str) -> str:
    """Break very long words to prevent FPDF wrapping crash."""
    words = line.split()
    safe_words = []
    for w in words:
        if len(w) > 45:
            safe_words.extend([w[i:i+45] for i in range(0, len(w), 45)])
        else:
            safe_words.append(w)
    return " ".join(safe_words)


def generate_pdf_from_markdown(md_text: str, subtitle: str = "") -> str:
    """
    Converts lesson text to a PDF file in the static directory.
    Handles both raw markdown and the block-structured format.
    Returns the filename of the generated PDF.
    """
    md_text = _sanitize_for_latin1(md_text)

    pdf = ClassGenPDF(subtitle=subtitle)
    pdf.add_page()
    pdf.set_font("helvetica", size=11)
    # Effective page width for multi_cell (avoids x-drift issues with width=0)
    epw = pdf.w - pdf.l_margin - pdf.r_margin

    # Check if this is block-structured content
    block_pattern = re.compile(
        r'Title:\s*\*{0,2}(.*?)\*{0,2}\s*\n'
        r'Summary:\s*(.*?)\n'
        r'Details:\s*(.*?)(?=\nTitle:|\Z)',
        re.DOTALL
    )

    # Try to find section blocks (content already has markers stripped by caller)
    blocks_found = list(block_pattern.finditer(md_text))

    if blocks_found:
        for block_match in blocks_found:
            title = block_match.group(1).replace('**', '').strip()
            summary = block_match.group(2).strip()
            details = block_match.group(3).strip()

            # Section title
            pdf.set_x(pdf.l_margin)
            pdf.set_font("helvetica", "B", 13)
            pdf.multi_cell(epw, 8, _safe_line(title))

            # Summary in italic
            pdf.set_x(pdf.l_margin)
            pdf.set_font("helvetica", "I", 11)
            pdf.multi_cell(epw, 6, _safe_line(summary))
            pdf.ln(2)

            # Details
            pdf.set_font("helvetica", size=11)
            for detail_line in details.split('\n'):
                detail_line = detail_line.strip()
                if not detail_line:
                    pdf.ln(3)
                    continue
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(epw, 6, _safe_line(detail_line.replace('**', '')))

            pdf.ln(6)
    else:
        # Fallback: basic markdown rendering
        for line in md_text.split('\n'):
            line = line.strip()
            if not line:
                pdf.ln(5)
                continue
            pdf.set_x(pdf.l_margin)
            if line.startswith('**') and line.endswith('**'):
                pdf.set_font("helvetica", "B", 13)
                pdf.multi_cell(epw, 8, line.replace('**', ''))
                pdf.set_font("helvetica", size=11)
            elif line.startswith('- ') or line.startswith('* '):
                pdf.set_x(20)
                pdf.multi_cell(epw - 10, 6, "- " + line[2:])
            else:
                pdf.multi_cell(epw, 6, _safe_line(line.replace('**', '')))

    filename = f"lesson_plan_{uuid.uuid4().hex[:8]}.pdf"
    file_path = os.path.join(static_dir, filename)
    pdf.output(file_path)
    return filename
