import os
import uuid
import re
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# Create static directory if it doesn't exist
static_dir = os.path.join(os.path.dirname(__file__), "static")
os.makedirs(static_dir, exist_ok=True)

class ClassGenPDF(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font("helvetica", "B", 15)
        # Title
        self.cell(0, 10, "ClassGen Lesson Plan", border=False, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        # Line break
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font("helvetica", "I", 8)
        # Page number
        self.cell(0, 10, f"Generated by ClassGen AI - Page {self.page_no()}", align="C")

def _sanitize_for_latin1(text: str) -> str:
    """Sanitize text for FPDF latin-1 encoded core fonts."""
    replacements = {
        '\u2014': '-',   # em dash
        '\u2013': '-',   # en dash
        '\u2018': "'",   # left single quote
        '\u2019': "'",   # right single quote
        '\u201c': '"',   # left double quote
        '\u201d': '"',   # right double quote
        '\u2022': '-',   # bullet
        '\u2026': '...', # ellipsis
    }
    for search, replace in replacements.items():
        text = text.replace(search, replace)
    return text.encode('latin-1', 'ignore').decode('latin-1')


def _safe_line(line: str) -> str:
    """Break very long words to prevent FPDF wrapping crash."""
    words = line.split()
    safe_words = []
    for w in words:
        if len(w) > 45:
            safe_words.extend([w[i:i+45] for i in range(0, len(w), 45)])
        else:
            safe_words.append(w)
    return " ".join(safe_words)


# Human-readable labels for block type markers
BLOCK_TYPE_LABELS = {
    'HOOK': 'Lesson Opener',
    'FACT': 'Key Fact',
    'APPLICATION': 'Real-World Connection',
    'ACTIVITY': 'Classroom Activity',
    'HOMEWORK': 'Homework',
}


def generate_pdf_from_markdown(md_text: str) -> str:
    """
    Converts lesson text to a PDF file in the static directory.
    Handles both raw markdown and the block-structured format.
    Returns the filename of the generated PDF.
    """
    md_text = _sanitize_for_latin1(md_text)

    pdf = ClassGenPDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=11)

    # Check if this is block-structured content
    block_pattern = re.compile(
        r'Title:\s*\*{0,2}(.*?)\*{0,2}\s*\n'
        r'Summary:\s*(.*?)\n'
        r'Details:\s*(.*?)(?=\n\n|\Z)',
        re.DOTALL
    )

    # Try to find section blocks (content already has markers stripped by caller)
    blocks_found = list(block_pattern.finditer(md_text))

    if blocks_found:
        for block_match in blocks_found:
            title = block_match.group(1).replace('**', '').strip()
            summary = block_match.group(2).strip()
            details = block_match.group(3).strip()

            # Section title
            pdf.set_font("helvetica", "B", 13)
            pdf.multi_cell(0, 8, _safe_line(title))

            # Summary in italic
            pdf.set_font("helvetica", "I", 11)
            pdf.multi_cell(0, 6, _safe_line(summary))
            pdf.ln(2)

            # Details
            pdf.set_font("helvetica", size=11)
            for detail_line in details.split('\n'):
                detail_line = detail_line.strip()
                if not detail_line:
                    pdf.ln(3)
                    continue
                pdf.multi_cell(0, 6, _safe_line(detail_line.replace('**', '')))

            pdf.ln(6)
    else:
        # Fallback: basic markdown rendering
        for line in md_text.split('\n'):
            line = line.strip()
            if not line:
                pdf.ln(5)
                continue
            if line.startswith('**') and line.endswith('**'):
                pdf.set_font("helvetica", "B", 13)
                pdf.multi_cell(0, 8, line.replace('**', ''))
                pdf.set_font("helvetica", size=11)
            elif line.startswith('- ') or line.startswith('* '):
                pdf.set_x(20)
                pdf.multi_cell(0, 6, "- " + line[2:])
            else:
                pdf.multi_cell(0, 6, _safe_line(line.replace('**', '')))

    filename = f"lesson_plan_{uuid.uuid4().hex[:8]}.pdf"
    file_path = os.path.join(static_dir, filename)
    pdf.output(file_path)
    return filename
